2020-09-10 20:58:58.375 +02:00 [Error] LogItem { Timestamp: 09/10/2020 20:58:58, Message: "The method or operation is not implemented.", NomApplication: "Tracking", Layer: "Controleur", Location: null, MethodName: "Nom de la méthode : MoveNext Nom du fichier : C:\Projets\arram-back\arram-back\Arram.Core.API\Controllers\LicenceController.cs Numero de ligne : 126", Hostname: null, UserId: null, UserName: null, CustomerId: null, ClientId: 0, CustomerName: null, ElapsedMilliseconds: null, Exception: NotImplementedException { TargetSite: Arram.Core.DAL.Entities.Licence ToEntity(Arram.Core.DTO.LicenceDTO, Boolean), StackTrace: "   at Arram.Core.Business.Mappings.MapLicence.ToEntity(LicenceDTO objet, Boolean v) in C:\Projets\arram-back\arram-back\Arram.Core.Business\Mappings\Entity\MapLicence.cs:line 13
   at Arram.Core.Business.LicenceLogic.CreateAsync(LicenceDTO objet) in C:\Projets\arram-back\arram-back\Arram.Core.Business\LicenceLogic.cs:line 66
   at Arram.Core.API.Controllers.LicenceController.Post(LicenceDTO objet) in C:\Projets\arram-back\arram-back\Arram.Core.API\Controllers\LicenceController.cs:line 126", Message: "The method or operation is not implemented.", Data: [], InnerException: null, HelpLink: null, Source: "Arram.Core.Business", HResult: -2147467263 }, CorrelationId: null, AdditionalInfo: null, AlerteEmail: False }
2020-09-10 21:43:10.016 +02:00 [Error] LogItem { Timestamp: 09/10/2020 21:42:53, Message: "Unknown error (0x89c50107)", NomApplication: "Tracking", Layer: "Repository", Location: null, MethodName: "Nom de la méthode : MoveNext Nom du fichier : C:\Projets\arram-back\arram-back\Arram.Core.Repo\Repositories\LicenceRepository.cs Numero de ligne : 34", Hostname: null, UserId: null, UserName: null, CustomerId: null, ClientId: 0, CustomerName: null, ElapsedMilliseconds: null, Exception: SqlException { Errors: [SqlError { Source: "Core Microsoft SqlClient Data Provider", Number: -1983577849, State: 0, Class: 20, Server: "", Message: "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. L'instance de base de données locale spécifiée n'existe pas.
)", Procedure: null, LineNumber: 0 }], ClientConnectionId: 00000000-0000-0000-0000-000000000000, Class: 20, LineNumber: 0, Number: -1983577849, Procedure: null, Server: "", State: 0, Source: "Core Microsoft SqlClient Data Provider", ErrorCode: -2146232060, TargetSite: Void .ctor(Microsoft.Data.ProviderBase.DbConnectionPoolIdentity, Microsoft.Data.SqlClient.SqlConnectionString, Microsoft.Data.SqlClient.SqlCredential, System.Object, System.String, System.Security.SecureString, Boolean, Microsoft.Data.SqlClient.SqlConnectionString, Microsoft.Data.SqlClient.SessionData, Boolean, System.String, Microsoft.Data.ProviderBase.DbConnectionPool, Microsoft.Data.SqlClient.SqlAuthenticationProviderManager), StackTrace: "   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Arram.Core.Repo.Repositories.LicenceRepository.GetAsync(Int32 id) in C:\Projets\arram-back\arram-back\Arram.Core.Repo\Repositories\LicenceRepository.cs:line 34", Message: "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. L'instance de base de données locale spécifiée n'existe pas.
)", Data: [DictionaryEntry { Key: "HelpLink.ProdName", Value: "Microsoft SQL Server" }, DictionaryEntry { Key: "HelpLink.EvtSrc", Value: "MSSQLServer" }, DictionaryEntry { Key: "HelpLink.EvtID", Value: "-1983577849" }, DictionaryEntry { Key: "HelpLink.BaseHelpUrl", Value: "http://go.microsoft.com/fwlink" }, DictionaryEntry { Key: "HelpLink.LinkId", Value: "20476" }], InnerException: Win32Exception { NativeErrorCode: -1983577849, ErrorCode: -2147467259, TargetSite: null, StackTrace: null, Message: "Unknown error (0x89c50107)", Data: [], InnerException: null, HelpLink: null, Source: null, HResult: -2147467259 }, HelpLink: null, HResult: -2146232060 }, CorrelationId: null, AdditionalInfo: null, AlerteEmail: False }
